version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000" # Adjusted external port to 3000 to match backend
    environment:
      - NODE_ENV=development
    command: ["yarn", "start"]

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3001" # Adjusted external port to 3001 to match backend
    environment:
      - NODE_ENV=development
    command: ["yarn", "run", "dev"]
